In [1]:
import crunch
crunch = crunch.load_notebook(__name__)
%cd shrill-mohamed
X_train, y_train, X_test = crunch.load_data()

loaded inline runner with module: <module '__main__'>
/home/ptl/internship/all_machine_learning/ranking/LambdaMart/shrill-mohamed
download data/X_train.parquet from https://datacrunch-com.s3.eu-west-1.amazonaws.com/production/adialab/data-releases/1/X_train.parquet
already exists: file length match
download data/y_train.parquet from https://datacrunch-com.s3.eu-west-1.amazonaws.com/production/adialab/data-releases/1/y_train.parquet
already exists: file length match
download data/X_test.parquet from https://datacrunch-com.s3.eu-west-1.amazonaws.com/production/adialab/data-releases/1/X_test_reduced.parquet
already exists: file length match

In [15]:
X_train

,date,id,0,1,2,3,4,5,6,7,...,451,452,453,454,455,456,457,458,459,460
0,0,dae29c8061b3176b9208f26afbb96e2ca50886db41902d...,-0.909515,0.388808,-1.535913,-0.133312,-1.826404,-0.532795,0.351273,0.158866,...,-0.731349,-0.456020,-0.257331,0.396074,0.318007,-0.538754,-0.625193,-0.753419,0.154403,1.069385
1,0,2f71f1b5d49fbd131351df95848dc91ab14662af62d4d0...,-0.107694,-0.097967,-0.539599,-0.331276,-0.942609,-0.054123,-1.212772,1.688034,...,0.610428,-0.984907,-0.429806,0.199055,0.202587,1.612578,0.302153,-0.165713,0.905807,0.083180
2,0,b8d41ef950b69f94c380410f59f47e15666c57b74573b6...,0.092316,0.052596,-0.652025,1.218241,0.382968,-0.861838,-0.318937,-0.744261,...,0.212365,-0.046016,1.147463,0.696961,-0.574426,1.255969,0.270394,1.272939,-0.643112,0.433585
3,0,cdce060d04ce28a551eaab653cc4b01f5ad878aeb932ec...,4.119639,1.018918,3.687519,1.597563,0.055918,-1.406041,0.652994,0.251138,...,1.254787,-1.155922,-1.108540,-2.046100,1.311100,-0.322965,0.999248,-1.238640,0.882844,-1.333590
4,0,86f6e6d9407ad3abfab91a3bbfb7ad71553e3f968765b8...,0.109644,-0.290280,-0.278987,-0.603259,0.136952,-1.725076,-0.062219,-0.183102,...,-2.007721,-0.482311,-0.269142,-0.899796,1.083332,0.674665,-1.095657,-0.402669,0.677189,0.319992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742665,268,5a18ddc0f252fa17cbd2a5bfe2f3786c0afb5052dd92be...,0.790984,1.560877,-0.328996,-0.190068,0.314971,-0.001609,0.313957,-0.315743,...,-1.450422,-1.044100,0.631455,-1.322626,-0.407846,0.578026,0.830650,1.414314,-0.845734,0.399335
742666,268,73c197cf1cb75641710562fe26d4f562c8228847a67949...,-1.129492,0.696247,-1.494771,-0.404022,0.909996,-0.658659,0.688591,1.634416,...,-0.475011,0.319023,-1.038112,0.222924,0.804017,-0.969177,-1.011879,-0.921781,-0.067543,0.491890
742667,268,bad7ff9ebc5579589e5ef36cb58f962c90c864fd3dfb22...,1.656413,-1.267060,0.748902,-0.196263,0.831206,-1.590837,3.079856,0.498583,...,-0.010330,-0.426130,-0.624393,-0.236483,-0.244052,1.280749,-2.001158,-1.036838,-1.959235,-2.534523
742668,268,5b968ca44ac0550be6f31470a96e572cd1c58d36cc26c7...,0.282704,0.156104,-1.165022,0.513334,-1.111948,-1.368465,-1.347184,-0.926533,...,0.411093,0.225324,-0.112838,-0.366831,-0.385833,-0.301606,0.395659,-0.895311,-0.819201,-0.996246
742669,268,a42ec1ac915edb35b440184ca52015bf3fdba53c631b1f...,-0.813073,-0.824916,-0.368725,0.136837,0.270865,0.710876,0.734015,-1.233695,...,0.134728,0.133413,-0.904207,-0.430508,-1.598422,-0.819337,0.012623,0.624302,-0.532539,0.105044

In [6]:
import numpy as np

In [7]:
X_train['display_rank'] = X_train.groupby('date').cumcount()
X_train

,date,id,0,1,2,3,4,5,6,7,...,452,453,454,455,456,457,458,459,460,display_rank
0,0,dae29c8061b3176b9208f26afbb96e2ca50886db41902d...,-0.909515,0.388808,-1.535913,-0.133312,-1.826404,-0.532795,0.351273,0.158866,...,-0.456020,-0.257331,0.396074,0.318007,-0.538754,-0.625193,-0.753419,0.154403,1.069385,0
1,0,2f71f1b5d49fbd131351df95848dc91ab14662af62d4d0...,-0.107694,-0.097967,-0.539599,-0.331276,-0.942609,-0.054123,-1.212772,1.688034,...,-0.984907,-0.429806,0.199055,0.202587,1.612578,0.302153,-0.165713,0.905807,0.083180,1
2,0,b8d41ef950b69f94c380410f59f47e15666c57b74573b6...,0.092316,0.052596,-0.652025,1.218241,0.382968,-0.861838,-0.318937,-0.744261,...,-0.046016,1.147463,0.696961,-0.574426,1.255969,0.270394,1.272939,-0.643112,0.433585,2
3,0,cdce060d04ce28a551eaab653cc4b01f5ad878aeb932ec...,4.119639,1.018918,3.687519,1.597563,0.055918,-1.406041,0.652994,0.251138,...,-1.155922,-1.108540,-2.046100,1.311100,-0.322965,0.999248,-1.238640,0.882844,-1.333590,3
4,0,86f6e6d9407ad3abfab91a3bbfb7ad71553e3f968765b8...,0.109644,-0.290280,-0.278987,-0.603259,0.136952,-1.725076,-0.062219,-0.183102,...,-0.482311,-0.269142,-0.899796,1.083332,0.674665,-1.095657,-0.402669,0.677189,0.319992,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742665,268,5a18ddc0f252fa17cbd2a5bfe2f3786c0afb5052dd92be...,0.790984,1.560877,-0.328996,-0.190068,0.314971,-0.001609,0.313957,-0.315743,...,-1.044100,0.631455,-1.322626,-0.407846,0.578026,0.830650,1.414314,-0.845734,0.399335,3993
742666,268,73c197cf1cb75641710562fe26d4f562c8228847a67949...,-1.129492,0.696247,-1.494771,-0.404022,0.909996,-0.658659,0.688591,1.634416,...,0.319023,-1.038112,0.222924,0.804017,-0.969177,-1.011879,-0.921781,-0.067543,0.491890,3994
742667,268,bad7ff9ebc5579589e5ef36cb58f962c90c864fd3dfb22...,1.656413,-1.267060,0.748902,-0.196263,0.831206,-1.590837,3.079856,0.498583,...,-0.426130,-0.624393,-0.236483,-0.244052,1.280749,-2.001158,-1.036838,-1.959235,-2.534523,3995
742668,268,5b968ca44ac0550be6f31470a96e572cd1c58d36cc26c7...,0.282704,0.156104,-1.165022,0.513334,-1.111948,-1.368465,-1.347184,-0.926533,...,0.225324,-0.112838,-0.366831,-0.385833,-0.301606,0.395659,-0.895311,-0.819201,-0.996246,3996
742669,268,a42ec1ac915edb35b440184ca52015bf3fdba53c631b1f...,-0.813073,-0.824916,-0.368725,0.136837,0.270865,0.710876,0.734015,-1.233695,...,0.133413,-0.904207,-0.430508,-1.598422,-0.819337,0.012623,0.624302,-0.532539,0.105044,3997

In [8]:
X_train['last_prediction'] = 0.0
X_train.sort_values(['date', 'last_prediction'], ascending=[True, False], kind='stable')
X_train['discount'] = 1 / np.log2(2 + X_train['display_rank'])
X_train['gain'] = (2**y_train['y'] - 1)
X_train["grade"] = y_train['y']
X_train[['date', 'display_rank', 'discount', 'grade', 'gain']]

        date  display_rank  discount     grade      gain
0          0             0  1.000000  0.192308  0.142590
1          0             1  0.630930 -0.476959 -0.281509
2          0             2  0.500000  0.080645  0.057491
3          0             3  0.430677  0.953125  0.936062
4          0             4  0.386853 -0.979263 -0.492761
...      ...           ...       ...       ...       ...
742665   268          3993  0.083584 -0.712248 -0.389632
742666   268          3994  0.083582  0.443895  0.360272
742667   268          3995  0.083579  0.302521  0.233298
742668   268          3996  0.083577 -0.726644 -0.395692
742669   268          3997  0.083574  0.695996  0.620003

[742670 rows x 5 columns]

In [9]:
swaps = X_train[:1000].merge(X_train[:1000], on='date', how='outer')
swaps

,date,id_x,0_x,1_x,2_x,3_x,4_x,5_x,6_x,7_x,...,456_y,457_y,458_y,459_y,460_y,display_rank_y,last_prediction_y,discount_y,gain_y,grade_y
0,0,dae29c8061b3176b9208f26afbb96e2ca50886db41902d...,-0.909515,0.388808,-1.535913,-0.133312,-1.826404,-0.532795,0.351273,0.158866,...,-0.538754,-0.625193,-0.753419,0.154403,1.069385,0,0.0,1.000000,0.142590,0.192308
1,0,dae29c8061b3176b9208f26afbb96e2ca50886db41902d...,-0.909515,0.388808,-1.535913,-0.133312,-1.826404,-0.532795,0.351273,0.158866,...,1.612578,0.302153,-0.165713,0.905807,0.083180,1,0.0,0.630930,-0.281509,-0.476959
2,0,dae29c8061b3176b9208f26afbb96e2ca50886db41902d...,-0.909515,0.388808,-1.535913,-0.133312,-1.826404,-0.532795,0.351273,0.158866,...,1.255969,0.270394,1.272939,-0.643112,0.433585,2,0.0,0.500000,0.057491,0.080645
3,0,dae29c8061b3176b9208f26afbb96e2ca50886db41902d...,-0.909515,0.388808,-1.535913,-0.133312,-1.826404,-0.532795,0.351273,0.158866,...,-0.322965,0.999248,-1.238640,0.882844,-1.333590,3,0.0,0.430677,0.936062,0.953125
4,0,dae29c8061b3176b9208f26afbb96e2ca50886db41902d...,-0.909515,0.388808,-1.535913,-0.133312,-1.826404,-0.532795,0.351273,0.158866,...,0.674665,-1.095657,-0.402669,0.677189,0.319992,4,0.0,0.386853,-0.492761,-0.979263
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
689723,1,ad560cb96d4d1fe739b2076bab9e9432c428616d25e53c...,-0.241504,-1.130108,-1.089153,-0.139987,-1.418430,0.146780,0.556533,-0.871093,...,0.074339,-0.579110,-0.583273,-0.402477,0.131134,187,0.0,0.132236,-0.392903,-0.720000
689724,1,ad560cb96d4d1fe739b2076bab9e9432c428616d25e53c...,-0.241504,-1.130108,-1.089153,-0.139987,-1.418430,0.146780,0.556533,-0.871093,...,0.780589,-0.907636,-0.054693,-0.494034,-1.108641,188,0.0,0.132103,0.092707,0.127907
689725,1,ad560cb96d4d1fe739b2076bab9e9432c428616d25e53c...,-0.241504,-1.130108,-1.089153,-0.139987,-1.418430,0.146780,0.556533,-0.871093,...,0.755279,-0.629173,-0.132027,-1.075000,-0.652262,189,0.0,0.131971,-0.203309,-0.327907
689726,1,ad560cb96d4d1fe739b2076bab9e9432c428616d25e53c...,-0.241504,-1.130108,-1.089153,-0.139987,-1.418430,0.146780,0.556533,-0.871093,...,-1.677803,1.375224,1.377650,-0.400408,0.178248,190,0.0,0.131840,-0.292893,-0.500000
689727,1,ad560cb96d4d1fe739b2076bab9e9432c428616d25e53c...,-0.241504,-1.130108,-1.089153,-0.139987,-1.418430,0.146780,0.556533,-0.871093,...,0.750631,-0.137509,0.686068,-0.776005,-0.796791,191,0.0,0.131710,-0.262628,-0.439535

In [10]:
swaps['delta'] = np.abs((swaps['discount_x'] - swaps['discount_y']) * (swaps['gain_x'] - swaps['gain_y']))
swaps[['date', 'display_rank_x', 'display_rank_y', 'delta']]

        date  display_rank_x  display_rank_y     delta
0          0               0               0  0.000000
1          0               0               1  0.156522
2          0               0               2  0.042550
3          0               0               3  0.451742
4          0               0               4  0.389564
...      ...             ...             ...       ...
689723     1             191             187  0.000069
689724     1             191             188  0.000140
689725     1             191             189  0.000015
689726     1             191             190  0.000004
689727     1             191             191  0.000000

[689728 rows x 4 columns]

In [11]:
swaps['rho'] = 1 / (1 + np.exp(swaps['last_prediction_x'] - swaps['last_prediction_y']))
swaps[['date', 'display_rank_x', 'display_rank_y', 'delta', 'last_prediction_x', 'last_prediction_y', 'rho']]

,date,display_rank_x,display_rank_y,delta,last_prediction_x,last_prediction_y,rho
0,0,0,0,0.000000,0.0,0.0,0.5
1,0,0,1,0.156522,0.0,0.0,0.5
2,0,0,2,0.042550,0.0,0.0,0.5
3,0,0,3,0.451742,0.0,0.0,0.5
4,0,0,4,0.389564,0.0,0.0,0.5
...,...,...,...,...,...,...,...
689723,1,191,187,0.000069,0.0,0.0,0.5
689724,1,191,188,0.000140,0.0,0.0,0.5
689725,1,191,189,0.000015,0.0,0.0,0.5
689726,1,191,190,0.000004,0.0,0.0,0.5
689727,1,191,191,0.000000,0.0,0.0,0.5

In [12]:
swaps['lambda'] = 0
slice_x_better =swaps[swaps['grade_x'] > swaps['grade_y']]
swaps.loc[swaps['grade_x'] > swaps['grade_y'], 'lambda'] = slice_x_better['delta'] * slice_x_better['rho']
swaps[['date', 'display_rank_x', 'display_rank_y', 'delta', 'last_prediction_x', 'last_prediction_y', 'rho', 'lambda']]

,date,display_rank_x,display_rank_y,delta,last_prediction_x,last_prediction_y,rho,lambda
0,0,0,0,0.000000,0.0,0.0,0.5,0.000000
1,0,0,1,0.156522,0.0,0.0,0.5,0.078261
2,0,0,2,0.042550,0.0,0.0,0.5,0.021275
3,0,0,3,0.451742,0.0,0.0,0.5,0.000000
4,0,0,4,0.389564,0.0,0.0,0.5,0.194782
...,...,...,...,...,...,...,...,...
689723,1,191,187,0.000069,0.0,0.0,0.5,0.000034
689724,1,191,188,0.000140,0.0,0.0,0.5,0.000000
689725,1,191,189,0.000015,0.0,0.0,0.5,0.000000
689726,1,191,190,0.000004,0.0,0.0,0.5,0.000002
689727,1,191,191,0.000000,0.0,0.0,0.5,0.000000

In [13]:
lambdas_x = swaps.groupby(['date', 'display_rank_x'])['lambda'].sum().rename('lambda')
lambdas_y = swaps.groupby(['date', 'display_rank_y'])['lambda'].sum().rename('lambda')
lambdas = lambdas_x - lambdas_y
lambdas
X_train = X_train[:1000].merge(lambdas, left_on=['date', 'display_rank'], right_on=['date', 'display_rank_x'], how='left')
X_train[['date', 'grade', 'lambda']]

     date     grade      lambda
0       0  0.192308   21.444089
1       0 -0.476959  -73.889577
2       0  0.080645   -3.573751
3       0  0.953125  105.250727
4       0 -0.979263  -60.532479
..    ...       ...         ...
995     1 -0.720000   -1.978887
996     1  0.127907    0.056526
997     1 -0.327907   -1.191232
998     1 -0.500000   -1.573459
999     1 -0.439535   -1.449657

[1000 rows x 3 columns]

In [2]:
def compute_lambdas(X_train,y_train):
    X_train = X_train.sort_values(['date', 'last_prediction'], ascending=[True, False], kind='stable')
    X_train['display_rank'] = X_train.groupby('date').cumcount()

    #TBD - How do generalize this to any metric?
    X_train['discount'] = 1 / np.log2(2 + X_train['display_rank'])
    X_train['grade'] = y_train['y']
    X_train['gain'] = (2**X_train['grade'] - 1)
    # swaps dataframe holds each pair-wise swap computed (shrink columns for memory?)   
    # Optimization of swaps = X_train.merge(X_train, on='date', how='outer')
    # to limit to just needed columns
    to_swap = X_train[['date', 'display_rank', 'grade', 'last_prediction', 'discount', 'gain']]
    #to_swap = X_train
    swaps = to_swap.merge(to_swap, on='date', how='outer')

    # delta - delta in DCG due to swap
    swaps['delta'] = np.abs((swaps['discount_x'] - swaps['discount_y']) * (swaps['gain_x'] - swaps['gain_y']))
    
    # rho - based on current model prediction delta
    swaps['rho'] = 1 / (1 + np.exp(swaps['last_prediction_x'] - swaps['last_prediction_y']))
    
    # If you want to be pure gradient boosting, weight reweights each models prediction
    # I haven't found this to matter in practice
    swaps['weight'] = swaps['rho'] * (1.0 - swaps['rho']) * swaps['delta']

    # Compute lambdas (the next model in ensemble's predictors) when grade_x > grade_y
    swaps['lambda'] = 0
    slice_x_better =swaps[swaps['grade_x'] > swaps['grade_y']]
    swaps.loc[swaps['grade_x'] > swaps['grade_y'], 'lambda'] = slice_x_better['delta'] * slice_x_better['rho']
    
    # accumulate lambdas and add back to model
    lambdas_x = swaps.groupby(['date', 'display_rank_x'])['lambda'].sum().rename('lambda')
    lambdas_y = swaps.groupby(['date', 'display_rank_y'])['lambda'].sum().rename('lambda')

    weights_x = swaps.groupby(['date', 'display_rank_x'])['weight'].sum().rename('weight')
    weights_y = swaps.groupby(['date', 'display_rank_y'])['weight'].sum().rename('weight')
    
    weights = weights_x + weights_y
    lambdas = lambdas_x - lambdas_y

    X_train = X_train.merge(lambdas, 
                                                left_on=['date', 'display_rank'], 
                                                right_on=['date', 'display_rank_x'], 
                                                how='left')
    X_train = X_train.merge(weights, 
                                                left_on=['date', 'display_rank'], 
                                                right_on=['date', 'display_rank_x'], 
                                                how='left')

    return X_train

In [5]:
from sklearn.tree import DecisionTreeRegressor
import pandas as pd
import numpy as np

ensemble=[]
def lambda_mart_pure(X_train, rounds=20,
                     learning_rate=0.1, max_leaf_nodes=8):


    lambdas_per_query = X_train.copy()
    lambdas_per_query['last_prediction'] = 0.0

    for i in range(0, rounds):
        print(f"round {i}")

        # ------------------
        #1. Build pair-wise predictors for this round
        lambdas_per_query = compute_lambdas(lambdas_per_query,y_train)

        # ------------------
        #2. Train a regression tree on this round's lambdas
        features = lambdas_per_query.iloc[:,2:463]
        new_tree = DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes)
        new_tree.fit(features, lambdas_per_query['lambda'])    

        # -------------------
        #4. Add to ensemble, recreate last prediction
        ensemble.append(new_tree)
        next_predictions = new_tree.predict(features)
        lambdas_per_query['last_prediction'] += (next_predictions * learning_rate) 
        
        print(lambdas_per_query.loc[0, ['grade', 'last_prediction']])
        
        print("Train DCGs")
        lambdas_per_query['discounted_gain'] = lambdas_per_query['gain'] * lambdas_per_query['discount'] 
        dcg = lambdas_per_query[lambdas_per_query['display_rank'] < 10].groupby('date')['discounted_gain'].sum().mean()
        print("mean   ", dcg)
        print("----------")
        
        lambdas_per_query = lambdas_per_query.drop(['lambda', 'weight'], axis=1)
    return lambdas_per_query

In [6]:
lambdas_per_query = lambda_mart_pure(X_train=X_train[:50000], rounds=10, max_leaf_nodes=10, learning_rate=0.01)

round 0

:

:

In [51]:
learning_rate=0.1
y_predicted = y_train[10000:15000].copy()
y_predicted.loc[:,"y"] = 0
features = X_train.iloc[10000:15000,2:463]
for tree in ensemble : 
    predictions = tree.predict(features)
    y_predicted.loc[:,'y'] += learning_rate*predictions

In [49]:
from scipy.stats import spearmanr

In [52]:
from scipy.stats import spearmanr

score = spearmanr(y_predicted["y"],y_train.iloc[10000:15000,-1])[0]*100
score

0.6496621820539209

In [44]:
print(score)

5.553606950062598